import type { LegalContent } from "@/types/content";

/**
 * Transcribed verbatim from https://axieonex.com/privacy-policy,
 * /terms-of-service, and /cookies-policy (see docs/ROUTE_INVENTORY.md).
 */
export const LEGAL_CONTENT: Record<string, LegalContent> = {
  "privacy-policy": {
    slug: "privacy-policy",
    title: "Privacy Policy",
    tagline: "We are committed to protecting your privacy and personal data.",
    lastUpdated: "LAST UPDATED: DECEMBER 13, 2025",
    metaDescription: "Read Axieonex Sales' Privacy Policy to understand how we collect, use, and protect your personal data.",
    sections: [
      { number: "1", heading: "Introduction", paragraphs: ["Welcome to Axieonex Sales. We respect your privacy and are committed to protecting your personal data. This Privacy Policy will inform you as to how we look after your personal data when you visit our website (axieonexsales.net) and tell you about your privacy rights and how the law protects you. By using our Service, you agree to the collection and use of information in accordance with this policy."] },
      { number: "2", heading: "Information We Collect", paragraphs: ["We collect several different types of information for various purposes to provide and improve our Service to you:", "Personal Data: While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ('Personal Data'). This may include, but is not limited to: Email address, First name and last name, Phone number, Business name, and Cookies and Usage Data.", "Usage Data: We may also collect information how the Service is accessed and used ('Usage Data'). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data."] },
      { number: "3", heading: "How We Use Your Information", paragraphs: ["Axieonex Sales uses the collected data for various purposes:", "To provide and maintain the Service", "To notify you about changes to our Service", "To allow you to participate in interactive features of our Service when you choose to do so", "To provide customer care and support", "To provide analysis or valuable information so that we can improve the Service", "To monitor the usage of the Service", "To detect, prevent and address technical issues"] },
      { number: "4", heading: "Legal Basis for Processing", paragraphs: ["If you are from the European Economic Area (EEA), Axieonex Sales's legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it. We may process your Personal Data because: We need to perform a contract with you; You have given us permission to do so; The processing is in our legitimate interests and it's not overridden by your rights; or To comply with the law."] },
      { number: "5", heading: "Information Sharing and Disclosure", paragraphs: ["We do not sell your personal data. However, we may share your information with third-party service providers to facilitate our Service, to provide the Service on our behalf, to perform Service-related services, or to assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose."] },
      { number: "6", heading: "Data Retention", paragraphs: ["Axieonex Sales will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies."] },
      { number: "7", heading: "Your Data Protection Rights", paragraphs: ["Axieonex Sales aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. Whenever made possible, you can update your Personal Data directly within your account settings section. If you are unable to change your Personal Data, please contact us to make the required changes. You have the right: To access and receive a copy of the Personal Data we hold about you; To rectify any Personal Data held about you that is inaccurate; To request the deletion of Personal Data held about you."] },
      { number: "8", heading: "International Data Transfers", paragraphs: ["Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction. If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there."] },
      { number: "9", heading: "Security of Your Data", paragraphs: ["The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security. We implement appropriate technical and organizational measures to ensure a level of security appropriate to the risk."] },
      { number: "10", heading: "Children's Privacy", paragraphs: ["Our Service does not address anyone under the age of 18 ('Children'). We do not knowingly collect personally identifiable information from anyone under the age of"] },
      { number: "18", heading: "If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.", paragraphs: [] },
      { number: "11", heading: "Changes to This Privacy Policy", paragraphs: ["We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the 'effective date' at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes."] },
      { number: "12", heading: "Third-Party Websites", paragraphs: ["Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services."] },
      { number: "13", heading: "Cookie Policy", paragraphs: ["We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. Cookies are files with small amount of data which may include an anonymous unique identifier. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. For more detailed information, please refer to our Cookies Policy."] },
      { number: "14", heading: "California Privacy Rights (CCPA)", paragraphs: ["If you are a California resident, you have specific rights regarding your personal information under the California Consumer Privacy Act (CCPA). You have the right to request that we disclose certain information to you about our collection and use of your personal information over the past 12 months. You have the right to request that we delete any of your personal information that we collected from you and retained, subject to certain exceptions."] },
      { number: "15", heading: "Contact Us", paragraphs: ["If you have any questions about this Privacy Policy, please contact us:", "By email: info@axieonexsales.net", "By visiting the contact page on our website: axieonexsales.net/contact", "© 2026 Axieonex Sales. All rights reserved."] },
    ],
  },
  "terms-of-service": {
    slug: "terms-of-service",
    title: "Terms of Service",
    tagline: "Please read these terms and conditions carefully before using our service.",
    lastUpdated: "LAST UPDATED: DECEMBER 13, 2025",
    metaDescription: "Read Axieonex Sales' Terms of Service regarding your use of our website and services.",
    sections: [
      { number: "1", heading: "Purchases", paragraphs: ["If you wish to purchase any product or service made available through the Service ('Purchase'), you may be asked to supply certain information relevant to your Purchase including, without limitation, your credit card number, the expiration date of your credit card, your billing address, and your shipping information. You represent and warrant that: (i) you have the legal right to use any credit card(s) or other payment method(s) in connection with any Purchase; and that (ii) the information you supply to us is true, correct and complete."] },
      { number: "2", heading: "Availability, Errors and Inaccuracies", paragraphs: ["We are constantly updating our offerings of products and services on the Service. The products or services available on our Service may be mispriced, described inaccurately, or unavailable, and we may experience delays in updating information on the Service and in our advertising on other web sites. We cannot and do not guarantee the accuracy or completeness of any information, including prices, product images, specifications, availability, and services. We reserve the right to change or update information and to correct errors, inaccuracies, or omissions at any time without prior notice."] },
      { number: "3", heading: "Subscriptions", paragraphs: ["Some parts of the Service are billed on a subscription basis ('Subscription(s)'). You will be billed in advance on a recurring and periodic basis ('Billing Cycle'). Billing cycles are set either on a monthly or annual basis, depending on the type of subscription plan you select when purchasing a Subscription. At the end of each Billing Cycle, your Subscription will automatically renew under the exact same conditions unless you cancel it or Axieonex Sales cancels it."] },
      { number: "4", heading: "Free Trial", paragraphs: ["Axieonex Sales may, at its sole discretion, offer a Subscription with a free trial for a limited period of time ('Free Trial'). You may be required to enter your billing information in order to sign up for the Free Trial. If you do enter your billing information when signing up for the Free Trial, you will not be charged by Axieonex Sales until the Free Trial has expired. On the last day of the Free Trial period, unless you cancelled your Subscription, you will be automatically charged the applicable Subscription fees for the type of Subscription you have selected."] },
      { number: "5", heading: "Fee Changes", paragraphs: ["Axieonex Sales, in its sole discretion and at any time, may modify the Subscription fees for the Subscriptions. Any Subscription fee change will become effective at the end of the then-current Billing Cycle. Axieonex Sales will provide you with reasonable prior notice of any change in Subscription fees to give you an opportunity to terminate your Subscription before such change becomes effective. Your continued use of the Service after the Subscription fee change comes into effect constitutes your agreement to pay the modified Subscription fee amount."] },
      { number: "6", heading: "Refunds", paragraphs: ["Except when required by law, paid Subscription fees are non-refundable. Certain refund requests for Subscriptions may be considered by Axieonex Sales on a case-by-case basis and granted at the sole discretion of Axieonex Sales."] },
      { number: "7", heading: "Accounts", paragraphs: ["When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service."] },
      { number: "8", heading: "Intellectual Property", paragraphs: ["The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of Axieonex Sales and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Axieonex Sales."] },
      { number: "9", heading: "Links To Other Web Sites", paragraphs: ["Our Service may contain links to third-party web sites or services that are not owned or controlled by Axieonex Sales. Axieonex Sales has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that Axieonex Sales shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services."] },
      { number: "10", heading: "Indemnification", paragraphs: ["You agree to defend, indemnify and hold harmless Axieonex Sales and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password; or b) a breach of these Terms.", "© 2026 Axieonex Sales. All rights reserved."] },
    ],
  },
  "cookies-policy": {
    slug: "cookies-policy",
    title: "Cookie Policy",
    tagline: "Transparency about how we use data to improve your experience.",
    lastUpdated: "LAST UPDATED: DECEMBER 13, 2025",
    metaDescription: "Learn about how Axieonex Sales uses cookies to improve your experience and manage your preferences.",
    sections: [
      { number: "1", heading: "What are cookies?", paragraphs: ["Cookies are small data files that are placed on your computer or mobile device when you visit a website. Cookies are widely used by website owners in order to make their websites work, or to work more efficiently, as well as to provide reporting information.", "Cookies set by the website owner (in this case, Axieonex) are called \"first-party cookies\". Cookies set by parties other than the website owner are called \"third-party cookies\". Third-party cookies enable third-party features or functionality to be provided on or through the website (e.g., advertising, interactive content, and analytics). The parties that set these third-party cookies can recognize your computer both when it visits the website in question and also when it visits certain other websites."] },
      { number: "2", heading: "Why do we use cookies?", paragraphs: ["We use first- and third-party cookies for several reasons. Some cookies are required for technical reasons in order for our Website to operate, and we refer to these as \"essential\" or \"strictly necessary\" cookies. Other cookies also enable us to track and target the interests of our users to enhance the experience on our Online Properties. Third parties serve cookies through our Website for advertising, analytics, and other purposes. This is described in more detail below."] },
      { number: "3", heading: "What types of cookies do we use?", paragraphs: ["Strictly Necessary Cookies", "These cookies are strictly necessary to provide you with services available through our Website and to use some of its features, such as access to secure areas.", "Performance & Analytics Cookies", "These cookies collect information that is used either in aggregate form to help us understand how our Website is being used or how effective our marketing campaigns are, or to help us customize our Website for you.", "Functionality Cookies", "These cookies are used to enhance the performance and functionality of our Website but are non-essential to their use. However, without these cookies, certain functionality (like videos) may become unavailable.", "Tailored Content Cookies", "These cookies help us customize the content and expressions you see on our site based on how you have interacted with our content previously.", "Targeting Cookies", "These cookies are used to make advertising messages more relevant to you. They perform functions like preventing the same ad from continuously reappearing, ensuring that ads are properly displayed for advertisers, and in some cases selecting advertisements that are based on your interests."] },
      { number: "4", heading: "How long will cookies stay on my browsing device?", paragraphs: ["The length of time a cookie will stay on your browsing device depends on whether it is a \"persistent\" or \"session\" cookie. Session cookies will only stay on your device until you stop browsing. Persistent cookies stay on your browsing device until they expire or are deleted. Most of the cookies we use are persistent and will expire between 30 minutes and two years from the date they are downloaded to your device."] },
      { number: "5", heading: "First- and Third-Party Cookies", paragraphs: ["First-party cookies are cookies that belong to Axieonex, while third-party cookies are cookies that another party places on your browsing device through our Website.", "We may allow third parties, such as analytics providers and ad networks, to place cookies on your device. These third parties may use cookies, web beacons, and other technologies to collect information about your use of our Website and other websites, including your IP address, web browser, pages viewed, time spent on pages, links clicked, and conversion information."] },
      { number: "6", heading: "How to control and delete cookies from your browser", paragraphs: ["You have the right to decide whether to accept or reject cookies. You can exercise your cookie rights by setting your preferences in the Cookie Consent Manager. The Cookie Consent Manager allows you to select which categories of cookies you accept or reject. Essential cookies cannot be rejected as they are strictly necessary to provide you with services.", "You can also set or amend your web browser controls to accept or refuse cookies. If you choose to reject cookies, you may still use our website though your access to some functionality and areas of our website may be restricted. As the means by which you can refuse cookies through your web browser controls vary from browser-to-browser, you should visit your browser's help menu for more information."] },
    ],
  },
};
