import type { Service } from "@/types/content";

/**
 * Ported verbatim from Axieonex Service Detail.dc.html's SERVICES data object
 * (per-slug problem/ai/human/control/receive/channels/quality/steps/faq) plus
 * Axieonex Services.dc.html's hub diagram data (ecosystem.*, which uses its own
 * distinct one-line blurbs, not the detail page's copy — the two pages are
 * genuinely different content in the approved design, not a duplication bug).
 */
export const SERVICES: Service[] = [
  {
    slug: "lead-generation",
    title: "Lead Generation",
    role: "INTAKE",
    accent: "#3E7BFA",
    visual: "radar",
    purpose:
      "Signal-driven sourcing of accounts that are actually ready to buy, not a purchased list run through generic automation.",
    problem:
      "Bought lists and generic scraping produce volume without relevance. Reps waste cycles on accounts with no real buying signal.",
    ai: "Continuously scans funding, hiring and technology-stack signals across your target market.",
    human: "Validates every lead against your ICP before it enters the system.",
    control: "You define the ICP, exclusions and account priorities.",
    receive: "A live, continuously refreshed pipeline of accounts worth pursuing.",
    channels: "Firmographic, funding, hiring and technology-stack signal, refreshed continuously across your target market.",
    quality: "Every account is checked against your ICP by a human analyst before it ever enters outreach.",
    steps: [
      { n: "01", text: "Define ICP and exclusion criteria together." },
      { n: "02", text: "Configure signal sources and scoring." },
      { n: "03", text: "Human analysts validate the highest-scoring accounts." },
      { n: "04", text: "Qualified accounts flow into outreach." },
    ],
    faqQ: "How is this different from a purchased list?",
    faqA: "Lists are static and decay immediately. This runs continuously against live market signal, so relevance does not expire.",
    ecosystem: {
      label: "Lead Gen",
      tag: "INTAKE",
      purpose: "Signal-driven sourcing of accounts that are actually ready to buy, not a purchased list run through generic automation.",
      aiPerforms: "Scans market signals continuously: funding, hiring, technology-stack changes.",
      humansPerform: "Validates every lead against your ICP before it enters the system.",
      youReceive: "A live pipeline of accounts worth pursuing, refreshed continuously.",
      x: 130,
      y: 120,
      labelSide: "below",
    },
  },
  {
    slug: "appointment-setting",
    title: "Appointment Setting",
    role: "QUALIFICATION",
    accent: "#E94FA8",
    visual: "calendar",
    purpose: "Meetings booked only once interest has been genuinely qualified, not booked to hit a volume target.",
    problem: "Volume-based appointment setting fills calendars with meetings that go nowhere, wasting your team's time.",
    ai: "Flags replies worth human attention immediately and prioritizes follow-up timing.",
    human: "Confirms real intent and fit before anything reaches your calendar.",
    control: 'You define what "qualified" means and who should be on the call.',
    receive: "A calendar of conversations worth having.",
    channels: "Works across every inbound reply channel: email, LinkedIn and calling.",
    quality: "A strategist confirms real intent by conversation before any meeting is booked.",
    steps: [
      { n: "01", text: "Define your qualification bar." },
      { n: "02", text: "Replies are triaged and prioritized." },
      { n: "03", text: "A strategist confirms intent by conversation." },
      { n: "04", text: "The meeting is booked directly on your calendar." },
    ],
    faqQ: "What counts as a qualified meeting?",
    faqA:
      "One where the prospect has confirmed a real need, timeline and role in the buying decision, defined together with you at kickoff.",
    ecosystem: {
      label: "Appointments",
      tag: "QUALIFICATION",
      purpose: "Meetings booked only once interest has been genuinely qualified.",
      aiPerforms: "Flags replies worth human attention immediately.",
      humansPerform: "Confirms real intent before anything reaches your calendar.",
      youReceive: "A calendar of conversations worth having, not just booked slots.",
      x: 440,
      y: 440,
      labelSide: "below",
    },
  },
  {
    slug: "hybrid-sdr",
    title: "Hybrid SDR Service",
    role: "FULL-STACK",
    accent: "#5CC8E8",
    visual: "rings",
    purpose: "The complete engine run end to end as your outbound function, replacing the need to build an internal team.",
    problem: "Building an internal SDR function means months of hiring and ramp before the first reliable pipeline appears.",
    ai: "Runs detection, orchestration and reporting continuously across every channel.",
    human: "Owns every conversation, decision and relationship end to end.",
    control: "You set strategy direction, brand voice and quarterly priorities.",
    receive: "A fully staffed outbound function without the hiring and management burden.",
    channels: "Email, LinkedIn, calling, signal intelligence and qualification, run as one function.",
    quality: "Weekly review with your team against the quality bar you define at kickoff.",
    steps: [
      { n: "01", text: "Full onboarding into your market and offer." },
      { n: "02", text: "The complete system is configured and launched." },
      { n: "03", text: "The team runs signal, outreach and qualification together." },
      { n: "04", text: "Continuous optimization from real results." },
    ],
    faqQ: "Does this replace hiring entirely?",
    faqA: "For most clients, yes, this is designed to be the complete outbound function rather than a supplement to one.",
    ecosystem: {
      label: "Hybrid SDR",
      tag: "FULL-STACK",
      purpose: "The complete engine run end to end as your outbound function, replacing an internal team.",
      aiPerforms: "Runs detection, orchestration and reporting continuously.",
      humansPerform: "Owns every conversation, decision and relationship.",
      youReceive: "A fully staffed outbound function without the hiring and management burden.",
      x: 240,
      y: 440,
      labelSide: "below",
    },
  },
  {
    slug: "cold-email",
    title: "Cold Email and Messaging",
    role: "OUTREACH",
    accent: "#8B5CF6",
    visual: "envelope",
    purpose: "Personalized sequences at scale, supervised for tone, timing and relevance rather than run on autopilot.",
    problem: "Generic templated email at scale gets ignored or marked as spam, damaging deliverability and brand.",
    ai: "Drafts and schedules personalized messaging at scale based on account signal.",
    human: "Reviews tone, timing and cadence before anything sends.",
    control: "You approve messaging voice and any claims made on your behalf.",
    receive: "A messaging engine that reads like your best rep wrote it.",
    channels: "Email sequencing, coordinated with LinkedIn and calling cadence.",
    quality: "A strategist reviews every sequence for tone and claims before it sends.",
    steps: [
      { n: "01", text: "Define voice and positioning together." },
      { n: "02", text: "Sequences are drafted against live signal." },
      { n: "03", text: "A strategist reviews before send." },
      { n: "04", text: "Replies are routed to human handling." },
    ],
    faqQ: "How is deliverability protected?",
    faqA: "Volume, cadence and personalization are all tuned to stay well within safe sending practices for your domain.",
    ecosystem: {
      label: "Cold Email",
      tag: "OUTREACH",
      purpose: "Personalized sequences at scale, supervised by strategists for tone, timing and relevance.",
      aiPerforms: "Drafts and schedules personalized messaging at scale.",
      humansPerform: "Reviews tone, timing and cadence before anything sends.",
      youReceive: "A messaging engine that sounds like your best rep, not a template.",
      x: 350,
      y: 60,
      labelSide: "above",
    },
  },
  {
    slug: "linkedin-outreach",
    title: "LinkedIn Outreach",
    role: "OUTREACH",
    accent: "#3E7BFA",
    visual: "network",
    purpose: "Social-first engagement coordinated with every other channel, not run as an isolated campaign.",
    problem: "LinkedIn outreach run in isolation from email and calling often repeats or contradicts other touchpoints.",
    ai: "Identifies the right moment and sequence for social touchpoints based on account activity.",
    human: "Handles every reply and relationship personally.",
    control: "You approve the profile voice and connection strategy.",
    receive: "Consistent presence in front of decision-makers where they already spend time.",
    channels: "Connection requests, messaging and engagement, coordinated with email and calling.",
    quality: "Every reply is handled personally by a human, never an automated responder.",
    steps: [
      { n: "01", text: "Align LinkedIn cadence with email and calling." },
      { n: "02", text: "Connection and message sequences launch." },
      { n: "03", text: "A human manages every reply." },
      { n: "04", text: "Engagement feeds back into account scoring." },
    ],
    faqQ: "Whose profile is used?",
    faqA: "Typically a designated team member's profile, configured and supervised by us, so the voice stays authentically yours.",
    ecosystem: {
      label: "LinkedIn",
      tag: "OUTREACH",
      purpose: "Social-first engagement coordinated with every other channel, not run in isolation.",
      aiPerforms: "Identifies the right moment and sequence for social touchpoints.",
      humansPerform: "Handles every reply and relationship personally.",
      youReceive: "Consistent presence in front of decision-makers where they already are.",
      x: 570,
      y: 120,
      labelSide: "above",
    },
  },
  {
    slug: "cold-calling",
    title: "Cold Calling",
    role: "EXECUTION",
    accent: "#E94FA8",
    visual: "waveform",
    purpose: "Experienced reps calling warm signal, not cold lists dialed at random.",
    problem: "Calling from a cold list wastes rep time and produces poor first impressions with prospects.",
    ai: "Prioritizes who to call and when, based on live signal strength and prior engagement.",
    human: "Makes every call and handles every objection personally.",
    control: "You define talk tracks, boundaries and escalation rules.",
    receive: "Conversations with people who already have a reason to listen.",
    channels: "Outbound calling, prioritized by live signal and prior multi-channel engagement.",
    quality: "Calls are made only by experienced human representatives, reviewed against your talk-track standards.",
    steps: [
      { n: "01", text: "Define call scripts and boundaries together." },
      { n: "02", text: "Calls are prioritized by signal strength." },
      { n: "03", text: "Experienced reps handle every conversation." },
      { n: "04", text: "Outcomes are logged and fed back into scoring." },
    ],
    faqQ: "Who makes the calls?",
    faqA: "Experienced human representatives, never a robocaller or synthetic voice.",
    ecosystem: {
      label: "Calling",
      tag: "EXECUTION",
      purpose: "Experienced reps calling warm signal, not cold lists pulled at random.",
      aiPerforms: "Prioritizes who to call and when, based on live signal strength.",
      humansPerform: "Makes every call and handles every objection.",
      youReceive: "Conversations with people who already have a reason to listen.",
      x: 600,
      y: 320,
      labelSide: "right",
    },
  },
  {
    slug: "presales-gtm",
    title: "Pre-Sales and GTM Strategy",
    role: "STRATEGY",
    accent: "#8B5CF6",
    visual: "blueprint",
    purpose: "Targeting, offer and channel design completed before a single message sends.",
    problem: "Outreach without a clear ICP, offer and channel plan produces activity without direction.",
    ai: "Models market segments and channel fit from available signal data.",
    human: "Designs positioning and go-to-market plan directly with you.",
    control: "You approve the final strategy and priority markets.",
    receive: "A revenue system built around your actual market, not a generic playbook.",
    channels: "Applies across every channel: it defines the plan that email, LinkedIn and calling then execute.",
    quality: "The final strategy is reviewed and approved by you before execution begins.",
    steps: [
      { n: "01", text: "Discovery on your business and market." },
      { n: "02", text: "ICP and segment modeling." },
      { n: "03", text: "Offer and channel plan is designed together." },
      { n: "04", text: "The plan becomes the blueprint for execution." },
    ],
    faqQ: "Is this a one-time engagement?",
    faqA: "It can be standalone, or it becomes the foundation for an ongoing Hybrid SDR engagement.",
    ecosystem: {
      label: "GTM Strategy",
      tag: "STRATEGY",
      purpose: "Targeting, offer and channel design completed before a single message sends.",
      aiPerforms: "Models market segments and channel fit from available data.",
      humansPerform: "Designs the positioning and go-to-market plan with you.",
      youReceive: "A revenue system built around your actual market, not a generic playbook.",
      x: 100,
      y: 320,
      labelSide: "left",
    },
  },
];

export function getService(slug: string): Service | undefined {
  return SERVICES.find((service) => service.slug === slug);
}

/** First 3 remaining services in declared order, matching the approved template's related-services logic. */
export function getRelatedServices(slug: string): Service[] {
  return SERVICES.filter((service) => service.slug !== slug).slice(0, 3);
}
