import type { ServiceContent } from "@/types/content";

/**
 * Transcribed verbatim from https://axieonex.com/services/* (see
 * docs/ROUTE_INVENTORY.md). Each service page on the live site follows the
 * same structure: What We Do / Why This Works / Who This Is For / CTA.
 */
export const SERVICES_CONTENT: Record<string, ServiceContent> = {
  "lead-generation": {
    slug: "lead-generation",
    title: "AI-Orchestrated Lead Generation for Consistent Pipeline Growth",
    metaDescription: "Generate consistent, high-quality B2B leads with Axieonex's AI-Orchestrated Sales Engine. Combining AI sourcing with human verification.",
    description: "Inconsistent lead quality and volume kill revenue growth. Designed for B2B SaaS, tech, and high-ticket service providers, our system replaces manual prospecting with a precise, AI-driven engine.",
    whatWeDo: ["Multi-channel sourcing across LinkedIn, verified databases, and intent signals.", "AI-powered scoring to prioritize prospects most likely to convert.", "Human verification layer to ensure data accuracy and relevance.", "Seamless CRM integration to pipe leads directly into your workflow.", "End-to-end tracking from initial contact to qualified opportunity."],
    whyThisWorksHeading: "Why This Works",
    whyThisWorks: "We combine the infinite scale of AI data processing with the nuanced judgment of human experts. This \"Hybrid Sales System\" ensures you never miss a signal while maintaining the high quality necessary for enterprise deals.",
    whoThisIsForHeading: "Who This Is For",
    whoThisIsFor: "Ideal for B2B SaaS companies, enterprise technology vendors, and high-ticket service firms who need a reliable, scalable flow of qualified leads without the overhead of hiring and training a massive internal research team.",
    badge: "Human-Executed, AI-Orchestrated",
    ctaHeading: "Ready to build a consistent pipeline?",
    ctaButton: "Start Your Campaign",
  },
  "appointment-setting": {
    slug: "appointment-setting",
    title: "AI-Orchestrated Appointment Setting for Predictable Pipeline Growth",
    metaDescription: "Fill your calendar with qualified meetings. Axieonex's AI-Orchestrated Appointment Setting service reduces no-shows and increases lead-to-meeting conversion.",
    description: "High no-show rates and low lead-to-meeting conversion drain sales productivity. We fix this by automating the chase and personalizing the coordination.",
    whatWeDo: ["Intelligent sequencing to engage prospects at the optimal time.", "Multi-touch outreach across email, phone, and LinkedIn.", "Seamless calendar management to book meetings directly into rep schedules.", "Automated confirmation flows to drastically reduce no-show rates.", "Real-time follow-up on engaged leads to maximize conversion speed."],
    whyThisWorksHeading: "Why This Works",
    whyThisWorks: "We use AI to identify the perfect moment to reach out, while our human team builds the relationship and handles the scheduling logistics. This ensures your sales team focuses only on closing, not chasing.",
    whoThisIsForHeading: "Who This Is For",
    whoThisIsFor: "Perfect for sales teams, B2B SaaS companies, and enterprise organizations that have leads but struggle to convert them into confirmed sales appointments efficiently.",
    badge: "Stop Chasing, Start Closing",
    ctaHeading: "Ready to fill your calendar?",
    ctaButton: "Start Your Campaign",
  },
  "hybrid-sdr": {
    slug: "hybrid-sdr",
    title: "Hybrid SDR Service: AI-Orchestrated, Human-Executed Outbound",
    metaDescription: "The best of both worlds: Axieonex's Hybrid SDR service combines AI-driven research with human-executed outreach for maximum efficiency and personalization.",
    description: "In-house SDR teams are expensive to hire and train, while pure automation lacks the human touch. Our hybrid model delivers the scale of AI with the conversion power of elite human reps.",
    whatWeDo: ["AI prospect research to identify decision-makers with active intent.", "Human-led outreach to ensure every message is relevant and compelling.", "Expert objection handling by trained SDRs, not rigid scripts.", "Relationship building that nurtures prospects until they are ready to buy.", "Comprehensive performance tracking to optimize the AI-human feedback loop."],
    whyThisWorksHeading: "Why This Works",
    whyThisWorks: "AI handles the drudgery—data entry, research, and initial sorting. Humans handle the influence—conversation, empathy, and negotiation. It’s significantly more efficient than traditional SDR teams.",
    whoThisIsForHeading: "Who This Is For",
    whoThisIsFor: "Ideal for growth-stage SaaS companies and scaling organizations that need to ramp up outbound sales quickly without the delay and risk of building a large internal team from scratch.",
    badge: "The Future of Sales Development",
    ctaHeading: "Ready to upgrade your sales team?",
    ctaButton: "Start Your Campaign",
  },
  "cold-email": {
    slug: "cold-email",
    title: "Cold Email & Messaging: AI-Orchestrated Campaigns with Human Touch",
    metaDescription: "Break through the inbox noise with Axieonex's AI-Orchestrated cold email campaigns. Personalized at scale, delivered by humans.",
    description: "Generic templates get deleted. To succeed in modern inboxes, you need hyper-personalization at scale. We solve this by combining AI research with human creativity.",
    whatWeDo: ["AI personalization that references specific prospect news, posts, and company updates.", "Human-written copy that is conversational, relevant, and persuasive.", "Intelligent sequencing that adapts based on prospect behavior and engagement.", "Rigorous A/B testing to constantly refine subject lines and value propositions.", "Deliverability management to ensure your messages actually hit the primary inbox."],
    whyThisWorksHeading: "Why This Works",
    whyThisWorks: "AI allows us to find the specific \"hooks\" for thousands of leads instantly, while our human copywriters craft the message so it feels like a 1-to-1 email from a colleague, not a robot.",
    whoThisIsForHeading: "Who This Is For",
    whoThisIsFor: "Built for B2B SaaS startups, digital agencies, and high-ticket service providers who need to start conversations with decision-makers without being ignored or marked as spam.",
    badge: "Personalization at Scale",
    ctaHeading: "Ready to get replies?",
    ctaButton: "Start Your Campaign",
  },
  "linkedin-outreach": {
    slug: "linkedin-outreach",
    title: "LinkedIn Outreach: AI-Orchestrated Campaigns for Decision-Maker Engagement",
    metaDescription: "Engage key decision-makers on the world's largest professional network. Axieonex's AI-Orchestrated LinkedIn campaigns drive real conversations.",
    description: "LinkedIn is the most powerful B2B channel, but manual outreach is too slow and generic bots get banned. We use a compliant, hybrid approach to build genuine connections.",
    whatWeDo: ["AI-driven targeting to identify the exact profiles matching your Ideal Customer Profile (ICP).", "Human-crafted connection requests and messages that feel personal and authentic.", "Active conversation management to pivot from casual chat to business interest.", "Strategic follow-up sequences that respect the platform's social nature.", "Profile optimization to ensure your rep looks like an authority, not a spammer."],
    whyThisWorksHeading: "Why This Works",
    whyThisWorks: "AI finds the right people faster than any human could, but humans are essential for building the trust required to get a response on a social platform. Our hybrid model maximizes both.",
    whoThisIsForHeading: "Who This Is For",
    whoThisIsFor: "Essential for B2B SaaS, enterprise sales teams, and professional services where the buyer is active on LinkedIn and relationships matter more than volume.",
    badge: "Connect with Decision Makers",
    ctaHeading: "Ready to expand your network?",
    ctaButton: "Start Your Campaign",
  },
  "cold-calling": {
    slug: "cold-calling",
    title: "Cold Calling: AI-Orchestrated, Human-Executed Sales Conversations",
    metaDescription: "Revive the most direct sales channel. Axieonex's AI-Orchestrated Cold Calling service combines data-driven prep with expert human execution.",
    description: "Scaling cold calling is notoriously difficult. Quality callers are expensive, and poor ones burn leads. We provide a managed, data-backed calling engine that delivers results.",
    whatWeDo: ["AI prospect research to arm callers with relevant talking points before they dial.", "Smart call timing optimization based on historical answer rate data.", "Expert human callers trained in consultative selling, not robotic script reading.", "Real-time coaching and quality assurance to maintain high performance.", "Detailed CRM logging of every interaction for full transparency."],
    whyThisWorksHeading: "Why This Works",
    whyThisWorks: "Success in cold calling comes from preparation and execution. AI handles the preparation at lightning speed, allowing our human experts to focus entirely on the execution of the conversation.",
    whoThisIsForHeading: "Who This Is For",
    whoThisIsFor: "Best suited for complex B2B sales, enterprise solution providers, and high-ticket service companies where a live conversation is often the only way to break through.",
    badge: "Direct Human Connection",
    ctaHeading: "Ready to pick up the phone?",
    ctaButton: "Start Your Campaign",
  },
  "presales-gtm": {
    slug: "presales-gtm",
    title: "Pre-Sales & Go-To-Market Strategy: Foundation for Outbound Success",
    metaDescription: "Don't launch blindly. Axieonex's Pre-Sales & GTM Strategy service builds the foundation for outbound success with clear ICPs, messaging, and positioning.",
    description: "Many companies launch outbound campaigns without clear positioning, messaging, or ICP definition—and fail. We build the strategic foundation that makes execution profitable.",
    whatWeDo: ["Deep market research to validate demand and identify untapped opportunities.", "Precise Ideal Customer Profile (ICP) definition to focus your resources.", "Offer positioning that differentiates you from competitors immediately.", "Messaging framework development for consistent, compelling communication.", "Sales enablement assets to arm your team (or ours) for the launch.", "Competitive analysis to understand exactly how to win in your niche."],
    whyThisWorksHeading: "Why This Works",
    whyThisWorks: "Execution without strategy is just noise. Strategic clarity leads to higher conversion rates and faster scaling because every message lands with the right person at the right time.",
    whoThisIsForHeading: "Who This Is For",
    whoThisIsFor: "Crucial for early-stage SaaS startups, companies launching new products, or established firms expanding into new markets who need to get it right the first time.",
    badge: "Preparation for Execution",
    ctaHeading: "Ready to define your strategy?",
    ctaButton: "Start Your Campaign",
  },
};
